---

- name: Installs nginx
  apt: pkg=nginx state=installed update_cache=true
  sudo: yes
  notify:
    - start nginx

- name: Configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes
