---

- name: Setup default user and SSH keys
  hosts: digital_ocean
  user: root

  vars_prompt:
    - name: user_password
      prompt: "Enter a password for the new user:"
      private: true

  roles:
    - sudo_user
