---

- name: create a new user
  user: name={{username}}
        state=present
        groups="sudo"
        password={{user_password}}
- name: Create the SSH directory.
  file: state=directory path=/home/{{username}}/.ssh/
- name: Copy SSH Public Key
  copy: src=~/.ssh/id_rsa.pub dest=/home/{{username}}/.ssh/authorized_keys
- name: Setup passwordless sudo
  template: src=sudoers.j2 dest=/etc/sudoers.d/adam validate='visudo -cf %s'

- name: Make home directory structure
  file: state=directory path=/home/{{username}}/{{item}}/
  with_items:
    - inbox
    - tmp
    - bin
