---

- name: Install iftop
  apt: name=iftop

- name: Install glances
  pip: name=glances

- name: Install htop
  apt: name=htop

- name: Install logwatch
  apt: name=logwatch
- name: Copy logwatch config
  template: src=logwatch.conf.j2 dest=/usr/share/logwatch/default.conf/logwatch.conf

- name: Install PSAD
  apt: name=psad
- name: Copy PSAD config
  template: src=psad.conf.j2 dest=/etc/psad/psad.conf
- name: Configure PSAD (IPtables)
  command: iptables -A INPUT -j LOG
- name: Configure PSAD (IPtables)
  command: iptables -A FORWARD -j LOG
- name: Configure PSAD (IP6tables)
  command: ip6tables -A INPUT -j LOG
- name: Configure PSAD (IP6tables)
  command: ip6tables -A FORWARD -j LOG
- name: Configure PSAD (update signatures)
  command: psad --sig-update

- name: Install Munin
  apt: name=munin
- name: Install Munin nginx config
  template: src=munin.nginx.j2 dest=/etc/nginx/sites-available/munin
- name: Enable munin nginx config
  file: src=/etc/nginx/sites-available/munin dest=/etc/nginx/sites-enabled/munin state=link
  notify:
    - restart nginx
