---

- name: Install git
  apt: name=git

- name: Copy global git config
  template: src=gitconfig.j2 dest=~/.gitconfig
- name: Copy global gitignore
  template: src=gitignore.j2 dest=~/.gitignore

- name: Get SCM Breeze
  git: repo="git://github.com/ndbroadbent/scm_breeze.git" dest=~/.scm_breeze
- name: Install SCM Breeze in bash
  command: echo "[ -s \"$HOME/.scm_breeze/scm_breeze.sh\" ] && source \"$HOME/.scm_breeze/scm_breeze.sh\"" >> ~/.bashrc
- name: Install SCM Breeze in ~/.zshrc
  command: echo "[ -s \"$HOME/.scm_breeze/scm_breeze.sh\" ] && source \"$HOME/.scm_breeze/scm_breeze.sh\"" >> ~/.zshrc removes=~/.zshrc
